# @USBAuthBundle/Resources/config/routing.yml
homepage:
  pattern:  /
  defaults: { _controller: USBAuthBundle:Default:index }

login:
  pattern:  /login

login_check:
  pattern:  /login_check

logout:
  pattern:  /logout

register:
  pattern: /registro
  defaults: { _controller: USBAuthBundle:Account:register }